version: '3.8'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: nbhung278
      POSTGRES_PASSWORD: nbhung278
      POSTGRES_DB: my_db
    ports:
      - 5434:5432
    expose:
      - 5434

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: nbhung278@gmail.com
      PGADMIN_DEFAULT_PASSWORD: nbhung278
    ports:
      - 8080:80
